### PR TITLE
Custom categories

### PR DESCRIPTION
**Pull request by davidtrak**
- DB now stores categories: user/{userId}/categories
- Settings page updates, closet page reads list and generates based on that.

### CODE REVIEW

**Review by sghose16 — COMMENTED** [review]
should we have some default categories because idk if its intuitive the first time you open the app to go to settings and add categories?

**Comment by davidtrak** [comment]
> should we have some default categories because idk if its intuitive the first time you open the app to go to settings and add categories?

done

**Review by lillytian — CHANGES_REQUESTED** [review]
Will need to display custom categories for the EditOutfit and CreateOutfit pages.

Also I think you'll have to fix the routing for the ShowAll pages with custom categories. Maybe use the feature in react-router-dom where you can pass in a parameter through the URL to query for what type the ShowAll page is? (See the EditOutfit routing.)

**Comment by davidtrak** [comment]
Show all pages now changed to all/category. 
 - user can technically change url to whatever they want, not doing dynamic route checking. allowing all routes.
 
 Edit / create outfits now reading db.

**Review by lillytian — APPROVED** [review]
lgtm but might conflict with john's settings stuff

**Pull request merged**
